import { useState, useEffect } from 'react';
import { FileText, Image, Download, File } from 'lucide-react';
import type { GeneratedArtifact } from '../types';

export default function GeneratedArtifacts() {
  const [artifacts, setArtifacts] = useState<GeneratedArtifact[]>([]);

  useEffect(() => {
    const mockArtifacts: GeneratedArtifact[] = [
      {
        id: '1',
        execution_id: '1',
        name: 'output_report.pdf',
        type: 'file',
        size: 2457600,
        storage_path: '/storage/executions/1/output_report.pdf',
        created_at: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        id: '2',
        execution_id: '1',
        name: 'visualization.png',
        type: 'image',
        size: 524288,
        storage_path: '/storage/executions/1/visualization.png',
        created_at: new Date(Date.now() - 3500000).toISOString(),
      },
      {
        id: '3',
        execution_id: '2',
        name: 'data_analysis.csv',
        type: 'file',
        size: 1048576,
        storage_path: '/storage/executions/2/data_analysis.csv',
        created_at: new Date(Date.now() - 1800000).toISOString(),
      },
    ];
    setArtifacts(mockArtifacts);
  }, []);

  const formatFileSize = (bytes: number) => {
    if (bytes >= 1073741824) return `${(bytes / 1073741824).toFixed(2)} GB`;
    if (bytes >= 1048576) return `${(bytes / 1048576).toFixed(2)} MB`;
    if (bytes >= 1024) return `${(bytes / 1024).toFixed(2)} KB`;
    return `${bytes} bytes`;
  };

  const getFileIcon = (type: string) => {
    switch (type) {
      case 'image':
        return <Image className="w-8 h-8 text-purple-500" />;
      case 'report':
        return <FileText className="w-8 h-8 text-blue-500" />;
      default:
        return <File className="w-8 h-8 text-gray-500" />;
    }
  };

  return (
    <div className="p-6">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Generated Artifacts</h1>
          <p className="text-gray-600 mt-1">Files and outputs generated by executions</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {artifacts.map((artifact) => (
          <div
            key={artifact.id}
            className="bg-white rounded-lg border border-gray-200 p-5 hover:shadow-md transition-shadow"
          >
            <div className="flex items-start justify-between mb-3">
              <div className="p-3 bg-gray-50 rounded-lg">{getFileIcon(artifact.type)}</div>
              <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                <Download className="w-5 h-5 text-gray-600" />
              </button>
            </div>

            <h3 className="text-sm font-semibold text-gray-900 mb-1 truncate">{artifact.name}</h3>
            <p className="text-xs text-gray-500 mb-3">{formatFileSize(artifact.size)}</p>

            <div className="space-y-2 pt-3 border-t border-gray-100">
              <div className="flex justify-between text-xs">
                <span className="text-gray-500">Type:</span>
                <span className="font-medium text-gray-900 capitalize">{artifact.type}</span>
              </div>
              <div className="flex justify-between text-xs">
                <span className="text-gray-500">Created:</span>
                <span className="font-medium text-gray-900">
                  {new Date(artifact.created_at).toLocaleDateString()}
                </span>
              </div>
            </div>
          </div>
        ))}
      </div>

      {artifacts.length === 0 && (
        <div className="bg-white rounded-lg border border-gray-200 p-12 text-center">
          <File className="w-12 h-12 text-gray-400 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-gray-900 mb-2">No Artifacts Generated</h3>
          <p className="text-gray-600">Artifacts will appear here once executions generate output files</p>
        </div>
      )}
    </div>
  );
}
